spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3307/loan_db?useSSL=false&allowPublicKeyRetrieval=true
    username: loan_user
    password: loanpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
